version: '3.9'
services:
#mongodb service

  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

#node Api service
  api:
    build: ./api
    ports:
    - 5000:5000
    environment:
      PORT: 5000
      MONGO_URL: mongodb+srv://team6:1234@ecommerce.cquauiy.mongodb.net/test
      DB_NAME: test
    depends_on:
      - mongo_db

# client service
  client:
    build: ./client-ecommerce
    ports:
    - 3000:3000
    environment:
      PORT: 3000

volumes:
  mongo_db: {}


